# Generated by Django 5.2.7 on 2025-10-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feature_alter_car_status_car_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='features',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.TextField(blank=True),
        ),
    ]
