# Generated by Django 5.2.7 on 2025-10-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_owner_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('reserved', 'Reserved'), ('used', 'Used'), ('new', 'New')], default='available', max_length=10, null=True),
        ),
    ]
