# Generated by Django 5.2.7 on 2025-10-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
