# Generated by Django 5.2.7 on 2025-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_carenquiry_remove_car_owner_remove_car_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='grade',
            field=models.CharField(blank=True, choices=[('6', '6'), ('5', '5'), ('4.5', '4.5'), ('4', '4'), ('3.5', '3.5'), ('3', '3'), ('R', 'R')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='grade',
            field=models.CharField(blank=True, choices=[('6', '6'), ('5', '5'), ('4.5', '4.5'), ('4', '4'), ('3.5', '3.5'), ('3', '3'), ('R', 'R')], max_length=3, null=True),
        ),
    ]
