# Generated by Django 5.2.7 on 2025-10-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_car_grade_alter_carenquiry_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carenquiry',
            name='color',
        ),
        migrations.RemoveField(
            model_name='carenquiry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carenquiry',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='carenquiry',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='carenquiry',
            name='make',
        ),
        migrations.RemoveField(
            model_name='carenquiry',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='carenquiry',
            name='model',
        ),
        migrations.RemoveField(
            model_name='carenquiry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='carenquiry',
            name='price',
        ),
        migrations.RemoveField(
            model_name='carenquiry',
            name='year',
        ),
        migrations.AddField(
            model_name='carenquiry',
            name='budget_range',
            field=models.CharField(choices=[('below_1m', 'Below Ksh 1M'), ('1m_2m', 'Ksh 1M - 2M'), ('2m_3m', 'Ksh 2M - 3M'), ('above_3m', 'Above Ksh 3M')], default='below_1m', max_length=20),
        ),
        migrations.AddField(
            model_name='carenquiry',
            name='vehicle_of_interest',
            field=models.CharField(default='below_1m', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='subject',
            field=models.CharField(default='Inquiry about car import', max_length=200),
        ),
    ]
