# Generated by Django 5.2.7 on 2025-10-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_masterclassenquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carenquiry',
            options={'verbose_name': 'Car Enquiry', 'verbose_name_plural': 'Car Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'verbose_name': 'Car Image', 'verbose_name_plural': 'Car Images'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name': 'General Enquiry', 'verbose_name_plural': 'General Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='masterclassenquiry',
            options={'verbose_name': 'Masterclass Enquiry', 'verbose_name_plural': 'Masterclass Enquiries'},
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('new', 'New')], default='available', max_length=10),
        ),
    ]
