# Generated by Django 5.2.7 on 2025-10-27 14:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_car_options_alter_carenquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
