# Generated by Django 5.2.7 on 2025-10-30 14:07

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_carimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
