# Generated by Django 5.2.7 on 2025-10-31 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short headline', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('author_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='testimonials/authors/')),
                ('testimonial_text', models.TextField(blank=True, help_text='Full written testimonial / excerpt', null=True)),
                ('long_content', models.TextField(blank=True, help_text='Optional long-form blog-like content (HTML/Markdown)', null=True)),
                ('youtube_video_url', models.URLField(blank=True, help_text='Full YouTube link (https://www.youtube.com/...) or youtu.be link', null=True)),
                ('youtube_video_id', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('layout_type', models.CharField(choices=[('text', 'Text Only'), ('video', 'Video Only'), ('both', 'Text + Video')], default='text', max_length=10)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Optional rating 1-5')),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show earlier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.testimonialcategory')),
                ('tags', models.ManyToManyField(blank=True, to='api.testimonialtag')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
