# Generated by Django 5.2.7 on 2025-10-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_testimonialcategory_testimonialtag_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_designation',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='long_content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='youtube_video_id',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='youtube_video_url',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_role',
            field=models.CharField(blank=True, help_text="Role or designation (e.g. 'First-time Buyer')", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='youtube_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste YouTube link if available.', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(blank=True, help_text='Name of the customer', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears earlier'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show as featured testimonial'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Rating from 1–5 stars'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Display on homepage testimonials section'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_text',
            field=models.TextField(blank=True, help_text="Customer's testimonial message.", null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(help_text="Short headline for testimonial (e.g. 'Amazing Experience!')", max_length=255),
        ),
        migrations.DeleteModel(
            name='TestimonialCategory',
        ),
        migrations.DeleteModel(
            name='TestimonialTag',
        ),
    ]
