# Generated by Django 5.2.7 on 2025-10-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_testimonial_category_remove_testimonial_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, help_text="Short headline for testimonial (e.g. 'Amazing Experience!')", max_length=255, null=True),
        ),
    ]
