# Generated by Django 5.2.7 on 2025-11-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_testimonial_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterclassenquiry',
            name='message',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
