# Generated by Django 5.2.7 on 2025-11-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_enquiry_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclassenquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
