# Generated by Django 5.2.7 on 2026-04-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_contactenquiry_delete_enquiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price',
            new_name='price_from',
        ),
        migrations.AddField(
            model_name='car',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
