# Generated by Django 5.2.7 on 2026-05-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_price_car_price_from_car_price_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('crossover', 'Crossover'), ('wagon', 'Wagon'), ('minivan', 'Minivan'), ('pickup', 'Pickup'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('van', 'Van')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_side',
            field=models.CharField(choices=[('rhd', 'Right Hand Drive'), ('lhd', 'Left Hand Drive')], default='rhd', max_length=3),
        ),
        migrations.AddField(
            model_name='car',
            name='import_type',
            field=models.CharField(choices=[('japan_import', 'Japan Import'), ('local', 'Local'), ('uk_import', 'UK Import')], default='japan_import', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='trim_levels',
            field=models.CharField(blank=True, help_text='Comma-separated trim levels e.g. X, G, Moda, TRD Sportivo', max_length=255, null=True),
        ),
    ]
