# Generated by Django 5.2.7 on 2026-05-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_car_body_type_car_drive_side_car_import_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.AlterField(
            model_name='car',
            name='import_type',
            field=models.CharField(choices=[('japan_import', 'Japan Import'), ('local', 'Local')], default='japan_import', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
