# Generated by Django 5.2.7 on 2026-05-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_car_color_remove_car_engine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
    ]
