# Generated by Django 5.2.7 on 2026-06-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_blogpost_content_alter_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='drive_side',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('available_to_import', 'Available to Import'), ('successful_import', 'Successful Import'), ('popular_in_kenya', 'Popular in Kenya')], default='available_to_import', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, help_text='e.g. Toyota, Nissan, Mazda', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, help_text='e.g. Prado, Note, Demio', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 2019', null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, help_text='Auto-filled if left blank', max_length=100, null=True),
        ),
    ]
