# Generated by Django 5.2.7 on 2026-06-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_car_drive_side_car_category_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
