# Generated by Django 5.2.7 on 2026-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_car_price_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='youtube_video_1',
            field=models.URLField(blank=True, help_text='YouTube video URL e.g. https://www.youtube.com/watch?v=xxxx', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='youtube_video_2',
            field=models.URLField(blank=True, help_text='Second YouTube video URL (optional)', max_length=500, null=True),
        ),
    ]
