# Generated by Django 5.2.7 on 2026-06-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_car_youtube_video_1_car_youtube_video_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='youtube_video_1_title',
            field=models.CharField(blank=True, help_text='e.g. Review after arrival', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='youtube_video_2_title',
            field=models.CharField(blank=True, help_text='e.g. Receiving the car', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='youtube_video_1',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='youtube_video_2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
