# Generated by Django 5.2.7 on 2026-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_car_youtube_video_1_title_car_youtube_video_2_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='youtube_id_2',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_id_3',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_id_4',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_title',
            field=models.CharField(blank=True, help_text='Optional title shown above this video', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_title_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_title_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_title_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_url_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_url_4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
