# Generated by Django 5.2.7 on 2026-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_blogpost_youtube_id_2_blogpost_youtube_id_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_id_2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_id_3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_id_4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_title_2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_title_3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_title_4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_url_2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_url_3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='youtube_url_4',
        ),
        migrations.AddField(
            model_name='car',
            name='youtube_video_3',
            field=models.URLField(blank=True, help_text='Third YouTube video URL (optional)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='youtube_video_3_title',
            field=models.CharField(blank=True, help_text='e.g. Full walkaround', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='youtube_video_4',
            field=models.URLField(blank=True, help_text='Fourth YouTube video URL (optional)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='youtube_video_4_title',
            field=models.CharField(blank=True, help_text='e.g. Customer testimonial', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='youtube_video_1',
            field=models.URLField(blank=True, help_text='YouTube video URL e.g. https://www.youtube.com/watch?v=xxxx', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='youtube_video_2',
            field=models.URLField(blank=True, help_text='Second YouTube video URL (optional)', max_length=500, null=True),
        ),
    ]
